//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Text.RegularExpressions;
using BusinessApp.Models;
using BusinessApp.ViewModels;

[assembly: EdmSchemaAttribute()]

namespace BusinessApp.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class software_projEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new software_projEntities object using the connection string found in the 'software_projEntities' section of the application configuration file.
        /// </summary>
        public software_projEntities() : base("name=software_projEntities", "software_projEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new software_projEntities object.
        /// </summary>
        public software_projEntities(string connectionString) : base(connectionString, "software_projEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new software_projEntities object.
        /// </summary>
        public software_projEntities(EntityConnection connection) : base(connection, "software_projEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<core_courses> core_courses
        {
            get
            {
                if ((_core_courses == null))
                {
                    _core_courses = base.CreateObjectSet<core_courses>("core_courses");
                }
                return _core_courses;
            }
        }
        private ObjectSet<core_courses> _core_courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cours> courses
        {
            get
            {
                if ((_courses == null))
                {
                    _courses = base.CreateObjectSet<cours>("courses");
                }
                return _courses;
            }
        }
        private ObjectSet<cours> _courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<course_sections> course_sections
        {
            get
            {
                if ((_course_sections == null))
                {
                    _course_sections = base.CreateObjectSet<course_sections>("course_sections");
                }
                return _course_sections;
            }
        }
        private ObjectSet<course_sections> _course_sections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<degree_requirements> degree_requirements
        {
            get
            {
                if ((_degree_requirements == null))
                {
                    _degree_requirements = base.CreateObjectSet<degree_requirements>("degree_requirements");
                }
                return _degree_requirements;
            }
        }
        private ObjectSet<degree_requirements> _degree_requirements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<elective_courses> elective_courses
        {
            get
            {
                if ((_elective_courses == null))
                {
                    _elective_courses = base.CreateObjectSet<elective_courses>("elective_courses");
                }
                return _elective_courses;
            }
        }
        private ObjectSet<elective_courses> _elective_courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<instructor> instructors
        {
            get
            {
                if ((_instructors == null))
                {
                    _instructors = base.CreateObjectSet<instructor>("instructors");
                }
                return _instructors;
            }
        }
        private ObjectSet<instructor> _instructors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<period> periods
        {
            get
            {
                if ((_periods == null))
                {
                    _periods = base.CreateObjectSet<period>("periods");
                }
                return _periods;
            }
        }
        private ObjectSet<period> _periods;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<required_courses> required_courses
        {
            get
            {
                if ((_required_courses == null))
                {
                    _required_courses = base.CreateObjectSet<required_courses>("required_courses");
                }
                return _required_courses;
            }
        }
        private ObjectSet<required_courses> _required_courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<students_table> students_table
        {
            get
            {
                if ((_students_table == null))
                {
                    _students_table = base.CreateObjectSet<students_table>("students_table");
                }
                return _students_table;
            }
        }
        private ObjectSet<students_table> _students_table;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student_courses> student_courses
        {
            get
            {
                if ((_student_courses == null))
                {
                    _student_courses = base.CreateObjectSet<student_courses>("student_courses");
                }
                return _student_courses;
            }
        }
        private ObjectSet<student_courses> _student_courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student_degrees> student_degrees
        {
            get
            {
                if ((_student_degrees == null))
                {
                    _student_degrees = base.CreateObjectSet<student_degrees>("student_degrees");
                }
                return _student_degrees;
            }
        }
        private ObjectSet<student_degrees> _student_degrees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<taken> takens
        {
            get
            {
                if ((_takens == null))
                {
                    _takens = base.CreateObjectSet<taken>("takens");
                }
                return _takens;
            }
        }
        private ObjectSet<taken> _takens;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the core_courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocore_courses(core_courses core_courses)
        {
            base.AddObject("core_courses", core_courses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocourses(cours cours)
        {
            base.AddObject("courses", cours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the course_sections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocourse_sections(course_sections course_sections)
        {
            base.AddObject("course_sections", course_sections);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the degree_requirements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodegree_requirements(degree_requirements degree_requirements)
        {
            base.AddObject("degree_requirements", degree_requirements);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the elective_courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToelective_courses(elective_courses elective_courses)
        {
            base.AddObject("elective_courses", elective_courses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the instructors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToinstructors(instructor instructor)
        {
            base.AddObject("instructors", instructor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the periods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToperiods(period period)
        {
            base.AddObject("periods", period);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the required_courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorequired_courses(required_courses required_courses)
        {
            base.AddObject("required_courses", required_courses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the students_table EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudents_table(students_table students_table)
        {
            base.AddObject("students_table", students_table);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the student_courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudent_courses(student_courses student_courses)
        {
            base.AddObject("student_courses", student_courses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the student_degrees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudent_degrees(student_degrees student_degrees)
        {
            base.AddObject("student_degrees", student_degrees);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the takens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotakens(taken taken)
        {
            base.AddObject("takens", taken);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="core_courses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class core_courses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new core_courses object.
        /// </summary>
        /// <param name="degree_id">Initial value of the Degree_id property.</param>
        /// <param name="course_id">Initial value of the Course_id property.</param>
        public static core_courses Createcore_courses(global::System.Int32 degree_id, global::System.Int32 course_id)
        {
            core_courses core_courses = new core_courses();
            core_courses.Degree_id = degree_id;
            core_courses.Course_id = course_id;
            return core_courses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Degree_id
        {
            get
            {
                return _Degree_id;
            }
            set
            {
                if (_Degree_id != value)
                {
                    OnDegree_idChanging(value);
                    ReportPropertyChanging("Degree_id");
                    _Degree_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Degree_id");
                    OnDegree_idChanged();
                }
            }
        }
        private global::System.Int32 _Degree_id;
        partial void OnDegree_idChanging(global::System.Int32 value);
        partial void OnDegree_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                if (_Course_id != value)
                {
                    OnCourse_idChanging(value);
                    ReportPropertyChanging("Course_id");
                    _Course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Course_id");
                    OnCourse_idChanged();
                }
            }
        }
        private global::System.Int32 _Course_id;
        partial void OnCourse_idChanging(global::System.Int32 value);
        partial void OnCourse_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="cours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cours object.
        /// </summary>
        /// <param name="course_id">Initial value of the Course_id property.</param>
        public static cours Createcours(global::System.Int32 course_id)
        {
            cours cours = new cours();
            cours.Course_id = course_id;
            return cours;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                if (_Course_id != value)
                {
                    OnCourse_idChanging(value);
                    ReportPropertyChanging("Course_id");
                    _Course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Course_id");
                    OnCourse_idChanged();
                }
            }
        }
        private global::System.Int32 _Course_id;
        partial void OnCourse_idChanging(global::System.Int32 value);
        partial void OnCourse_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Course_Name
        {
            get
            {
                return _Course_Name;
            }
            set
            {
                OnCourse_NameChanging(value);
                ReportPropertyChanging("Course_Name");
                _Course_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Course_Name");
                OnCourse_NameChanged();
            }
        }
        private global::System.String _Course_Name;
        partial void OnCourse_NameChanging(global::System.String value);
        partial void OnCourse_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Course_Credits
        {
            get
            {
                return _Course_Credits;
            }
            set
            {
                OnCourse_CreditsChanging(value);
                ReportPropertyChanging("Course_Credits");
                _Course_Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Course_Credits");
                OnCourse_CreditsChanged();
            }
        }
        private Nullable<global::System.Int32> _Course_Credits;
        partial void OnCourse_CreditsChanging(Nullable<global::System.Int32> value);
        partial void OnCourse_CreditsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="course_sections")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class course_sections : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new course_sections object.
        /// </summary>
        /// <param name="course_D_id">Initial value of the Course_D_id property.</param>
        public static course_sections Createcourse_sections(global::System.String course_D_id)
        {
            course_sections course_sections = new course_sections();
            course_sections.Course_D_id = course_D_id;
            return course_sections;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Course_D_id
        {
            get
            {
                return _Course_D_id;
            }
            set
            {
                if (_Course_D_id != value)
                {
                    OnCourse_D_idChanging(value);
                    ReportPropertyChanging("Course_D_id");
                    _Course_D_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Course_D_id");
                    OnCourse_D_idChanged();
                }
            }
        }
        private global::System.String _Course_D_id;
        partial void OnCourse_D_idChanging(global::System.String value);
        partial void OnCourse_D_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Course_Name
        {
            get
            {
                return _Course_Name;
            }
            set
            {
                OnCourse_NameChanging(value);
                ReportPropertyChanging("Course_Name");
                _Course_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Course_Name");
                OnCourse_NameChanged();
            }
        }
        private global::System.String _Course_Name;
        partial void OnCourse_NameChanging(global::System.String value);
        partial void OnCourse_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Course_Number
        {
            get
            {
                return _Course_Number;
            }
            set
            {
                OnCourse_NumberChanging(value);
                ReportPropertyChanging("Course_Number");
                _Course_Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Course_Number");
                OnCourse_NumberChanged();
            }
        }
        private global::System.String _Course_Number;
        partial void OnCourse_NumberChanging(global::System.String value);
        partial void OnCourse_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Course_Section
        {
            get
            {
                return _Course_Section;
            }
            set
            {
                OnCourse_SectionChanging(value);
                ReportPropertyChanging("Course_Section");
                _Course_Section = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Course_Section");
                OnCourse_SectionChanged();
            }
        }
        private global::System.String _Course_Section;
        partial void OnCourse_SectionChanging(global::System.String value);
        partial void OnCourse_SectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                OnCourse_idChanging(value);
                ReportPropertyChanging("Course_id");
                _Course_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Course_id");
                OnCourse_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Course_id;
        partial void OnCourse_idChanging(Nullable<global::System.Int32> value);
        partial void OnCourse_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Instructor_id
        {
            get
            {
                return _Instructor_id;
            }
            set
            {
                OnInstructor_idChanging(value);
                ReportPropertyChanging("Instructor_id");
                _Instructor_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Instructor_id");
                OnInstructor_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Instructor_id;
        partial void OnInstructor_idChanging(Nullable<global::System.Int32> value);
        partial void OnInstructor_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Term
        {
            get
            {
                return _Term;
            }
            set
            {
                OnTermChanging(value);
                ReportPropertyChanging("Term");
                _Term = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Term");
                OnTermChanged();
            }
        }
        private global::System.String _Term;
        partial void OnTermChanging(global::System.String value);
        partial void OnTermChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="degree_requirements")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class degree_requirements : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new degree_requirements object.
        /// </summary>
        /// <param name="degree_id">Initial value of the Degree_id property.</param>
        public static degree_requirements Createdegree_requirements(global::System.Int32 degree_id)
        {
            degree_requirements degree_requirements = new degree_requirements();
            degree_requirements.Degree_id = degree_id;
            return degree_requirements;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Degree_id
        {
            get
            {
                return _Degree_id;
            }
            set
            {
                if (_Degree_id != value)
                {
                    OnDegree_idChanging(value);
                    ReportPropertyChanging("Degree_id");
                    _Degree_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Degree_id");
                    OnDegree_idChanged();
                }
            }
        }
        private global::System.Int32 _Degree_id;
        partial void OnDegree_idChanging(global::System.Int32 value);
        partial void OnDegree_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Degree_Name
        {
            get
            {
                return _Degree_Name;
            }
            set
            {
                OnDegree_NameChanging(value);
                ReportPropertyChanging("Degree_Name");
                _Degree_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Degree_Name");
                OnDegree_NameChanged();
            }
        }
        private global::System.String _Degree_Name;
        partial void OnDegree_NameChanging(global::System.String value);
        partial void OnDegree_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total_Degree_Credits
        {
            get
            {
                return _Total_Degree_Credits;
            }
            set
            {
                OnTotal_Degree_CreditsChanging(value);
                ReportPropertyChanging("Total_Degree_Credits");
                _Total_Degree_Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total_Degree_Credits");
                OnTotal_Degree_CreditsChanged();
            }
        }
        private Nullable<global::System.Int32> _Total_Degree_Credits;
        partial void OnTotal_Degree_CreditsChanging(Nullable<global::System.Int32> value);
        partial void OnTotal_Degree_CreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Core_Course_Credits
        {
            get
            {
                return _Core_Course_Credits;
            }
            set
            {
                OnCore_Course_CreditsChanging(value);
                ReportPropertyChanging("Core_Course_Credits");
                _Core_Course_Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Core_Course_Credits");
                OnCore_Course_CreditsChanged();
            }
        }
        private Nullable<global::System.Int32> _Core_Course_Credits;
        partial void OnCore_Course_CreditsChanging(Nullable<global::System.Int32> value);
        partial void OnCore_Course_CreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Required_Course_Credits
        {
            get
            {
                return _Required_Course_Credits;
            }
            set
            {
                OnRequired_Course_CreditsChanging(value);
                ReportPropertyChanging("Required_Course_Credits");
                _Required_Course_Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Required_Course_Credits");
                OnRequired_Course_CreditsChanged();
            }
        }
        private Nullable<global::System.Int32> _Required_Course_Credits;
        partial void OnRequired_Course_CreditsChanging(Nullable<global::System.Int32> value);
        partial void OnRequired_Course_CreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Elective_Course_Credits
        {
            get
            {
                return _Elective_Course_Credits;
            }
            set
            {
                OnElective_Course_CreditsChanging(value);
                ReportPropertyChanging("Elective_Course_Credits");
                _Elective_Course_Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elective_Course_Credits");
                OnElective_Course_CreditsChanged();
            }
        }
        private Nullable<global::System.Int32> _Elective_Course_Credits;
        partial void OnElective_Course_CreditsChanging(Nullable<global::System.Int32> value);
        partial void OnElective_Course_CreditsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="elective_courses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class elective_courses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new elective_courses object.
        /// </summary>
        /// <param name="degree_id">Initial value of the Degree_id property.</param>
        /// <param name="course_id">Initial value of the Course_id property.</param>
        public static elective_courses Createelective_courses(global::System.Int32 degree_id, global::System.Int32 course_id)
        {
            elective_courses elective_courses = new elective_courses();
            elective_courses.Degree_id = degree_id;
            elective_courses.Course_id = course_id;
            return elective_courses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Degree_id
        {
            get
            {
                return _Degree_id;
            }
            set
            {
                if (_Degree_id != value)
                {
                    OnDegree_idChanging(value);
                    ReportPropertyChanging("Degree_id");
                    _Degree_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Degree_id");
                    OnDegree_idChanged();
                }
            }
        }
        private global::System.Int32 _Degree_id;
        partial void OnDegree_idChanging(global::System.Int32 value);
        partial void OnDegree_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                if (_Course_id != value)
                {
                    OnCourse_idChanging(value);
                    ReportPropertyChanging("Course_id");
                    _Course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Course_id");
                    OnCourse_idChanged();
                }
            }
        }
        private global::System.Int32 _Course_id;
        partial void OnCourse_idChanging(global::System.Int32 value);
        partial void OnCourse_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="instructor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class instructor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new instructor object.
        /// </summary>
        /// <param name="instructor_id">Initial value of the Instructor_id property.</param>
        public static instructor Createinstructor(global::System.Int32 instructor_id)
        {
            instructor instructor = new instructor();
            instructor.Instructor_id = instructor_id;
            return instructor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [Required(ErrorMessage="Required")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Incorrect ID")]
        public global::System.Int32 Instructor_id
        {
            get
            {
                return _Instructor_id;
            }
            set
            {
                if (_Instructor_id != value)
                {
                    OnInstructor_idChanging(value);
                    ReportPropertyChanging("Instructor_id");
                    _Instructor_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Instructor_id");
                    OnInstructor_idChanged();
                }
            }
        }
        private global::System.Int32 _Instructor_id;
        partial void OnInstructor_idChanging(global::System.Int32 value);
        partial void OnInstructor_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Full_Name
        {
            get
            {
                return _Full_Name;
            }
            set
            {
                OnFull_NameChanging(value);
                ReportPropertyChanging("Full_Name");
                _Full_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Full_Name");
                OnFull_NameChanged();
            }
        }
        private global::System.String _Full_Name;
        partial void OnFull_NameChanging(global::System.String value);
        partial void OnFull_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [Required]
        [EmailValidation(ErrorMessage = "Not a valid email address")]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public global::System.String Phone_Number
        {
            get
            {
                return _Phone_Number;
            }
            set
            {
                OnPhone_NumberChanging(value);
                ReportPropertyChanging("Phone_Number");
                _Phone_Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone_Number");
                OnPhone_NumberChanged();
            }
        }
        private global::System.String _Phone_Number;
        partial void OnPhone_NumberChanging(global::System.String value);
        partial void OnPhone_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pref_Location
        {
            get
            {
                return _Pref_Location;
            }
            set
            {
                OnPref_LocationChanging(value);
                ReportPropertyChanging("Pref_Location");
                _Pref_Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pref_Location");
                OnPref_LocationChanged();
            }
        }
        private global::System.String _Pref_Location;
        partial void OnPref_LocationChanging(global::System.String value);
        partial void OnPref_LocationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="period")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class period : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new period object.
        /// </summary>
        /// <param name="trimester">Initial value of the Trimester property.</param>
        /// <param name="course_id">Initial value of the Course_id property.</param>
        public static period Createperiod(global::System.String trimester, global::System.Int32 course_id)
        {
            period period = new period();
            period.Trimester = trimester;
            period.Course_id = course_id;
            return period;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Trimester
        {
            get
            {
                return _Trimester;
            }
            set
            {
                if (_Trimester != value)
                {
                    OnTrimesterChanging(value);
                    ReportPropertyChanging("Trimester");
                    _Trimester = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Trimester");
                    OnTrimesterChanged();
                }
            }
        }
        private global::System.String _Trimester;
        partial void OnTrimesterChanging(global::System.String value);
        partial void OnTrimesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                if (_Course_id != value)
                {
                    OnCourse_idChanging(value);
                    ReportPropertyChanging("Course_id");
                    _Course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Course_id");
                    OnCourse_idChanged();
                }
            }
        }
        private global::System.Int32 _Course_id;
        partial void OnCourse_idChanging(global::System.Int32 value);
        partial void OnCourse_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="required_courses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class required_courses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new required_courses object.
        /// </summary>
        /// <param name="degree_id">Initial value of the Degree_id property.</param>
        /// <param name="course_id">Initial value of the Course_id property.</param>
        public static required_courses Createrequired_courses(global::System.Int32 degree_id, global::System.Int32 course_id)
        {
            required_courses required_courses = new required_courses();
            required_courses.Degree_id = degree_id;
            required_courses.Course_id = course_id;
            return required_courses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Degree_id
        {
            get
            {
                return _Degree_id;
            }
            set
            {
                if (_Degree_id != value)
                {
                    OnDegree_idChanging(value);
                    ReportPropertyChanging("Degree_id");
                    _Degree_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Degree_id");
                    OnDegree_idChanged();
                }
            }
        }
        private global::System.Int32 _Degree_id;
        partial void OnDegree_idChanging(global::System.Int32 value);
        partial void OnDegree_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                if (_Course_id != value)
                {
                    OnCourse_idChanging(value);
                    ReportPropertyChanging("Course_id");
                    _Course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Course_id");
                    OnCourse_idChanged();
                }
            }
        }
        private global::System.Int32 _Course_id;
        partial void OnCourse_idChanging(global::System.Int32 value);
        partial void OnCourse_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="student_courses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student_courses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student_courses object.
        /// </summary>
        /// <param name="student_D_id">Initial value of the Student_D_id property.</param>
        /// <param name="course_id">Initial value of the Course_id property.</param>
        public static student_courses Createstudent_courses(global::System.Int32 student_D_id, global::System.Int32 course_id)
        {
            student_courses student_courses = new student_courses();
            student_courses.Student_D_id = student_D_id;
            student_courses.Course_id = course_id;
            return student_courses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Student_D_id
        {
            get
            {
                return _Student_D_id;
            }
            set
            {
                if (_Student_D_id != value)
                {
                    OnStudent_D_idChanging(value);
                    ReportPropertyChanging("Student_D_id");
                    _Student_D_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Student_D_id");
                    OnStudent_D_idChanged();
                }
            }
        }
        private global::System.Int32 _Student_D_id;
        partial void OnStudent_D_idChanging(global::System.Int32 value);
        partial void OnStudent_D_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Course_id
        {
            get
            {
                return _Course_id;
            }
            set
            {
                if (_Course_id != value)
                {
                    OnCourse_idChanging(value);
                    ReportPropertyChanging("Course_id");
                    _Course_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Course_id");
                    OnCourse_idChanged();
                }
            }
        }
        private global::System.Int32 _Course_id;
        partial void OnCourse_idChanging(global::System.Int32 value);
        partial void OnCourse_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="student_degrees")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student_degrees : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student_degrees object.
        /// </summary>
        /// <param name="student_D_id">Initial value of the Student_D_id property.</param>
        public static student_degrees Createstudent_degrees(global::System.Int32 student_D_id)
        {
            student_degrees student_degrees = new student_degrees();
            student_degrees.Student_D_id = student_D_id;
            return student_degrees;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Student_D_id
        {
            get
            {
                return _Student_D_id;
            }
            set
            {
                if (_Student_D_id != value)
                {
                    OnStudent_D_idChanging(value);
                    ReportPropertyChanging("Student_D_id");
                    _Student_D_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Student_D_id");
                    OnStudent_D_idChanged();
                }
            }
        }
        private global::System.Int32 _Student_D_id;
        partial void OnStudent_D_idChanging(global::System.Int32 value);
        partial void OnStudent_D_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IONA_Student_id
        {
            get
            {
                return _IONA_Student_id;
            }
            set
            {
                OnIONA_Student_idChanging(value);
                ReportPropertyChanging("IONA_Student_id");
                _IONA_Student_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IONA_Student_id");
                OnIONA_Student_idChanged();
            }
        }
        private global::System.String _IONA_Student_id;
        partial void OnIONA_Student_idChanging(global::System.String value);
        partial void OnIONA_Student_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Degree_id
        {
            get
            {
                return _Degree_id;
            }
            set
            {
                OnDegree_idChanging(value);
                ReportPropertyChanging("Degree_id");
                _Degree_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Degree_id");
                OnDegree_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Degree_id;
        partial void OnDegree_idChanging(Nullable<global::System.Int32> value);
        partial void OnDegree_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Credits_Complete
        {
            get
            {
                return _Credits_Complete;
            }
            set
            {
                OnCredits_CompleteChanging(value);
                ReportPropertyChanging("Credits_Complete");
                _Credits_Complete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Credits_Complete");
                OnCredits_CompleteChanged();
            }
        }
        private Nullable<global::System.Int32> _Credits_Complete;
        partial void OnCredits_CompleteChanging(Nullable<global::System.Int32> value);
        partial void OnCredits_CompleteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="students_table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class students_table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new students_table object.
        /// </summary>
        /// <param name="iONA_Student_id">Initial value of the IONA_Student_id property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static students_table Createstudents_table(global::System.String iONA_Student_id, global::System.String status)
        {
            students_table students_table = new students_table();
            students_table.IONA_Student_id = iONA_Student_id;
            students_table.Status = status;
            return students_table;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IONA_Student_id
        {
            get
            {
                return _IONA_Student_id;
            }
            set
            {
                if (_IONA_Student_id != value)
                {
                    OnIONA_Student_idChanging(value);
                    ReportPropertyChanging("IONA_Student_id");
                    _IONA_Student_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IONA_Student_id");
                    OnIONA_Student_idChanged();
                }
            }
        }
        private global::System.String _IONA_Student_id;
        partial void OnIONA_Student_idChanging(global::System.String value);
        partial void OnIONA_Student_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Full_Name
        {
            get
            {
                return _Full_Name;
            }
            set
            {
                OnFull_NameChanging(value);
                ReportPropertyChanging("Full_Name");
                _Full_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Full_Name");
                OnFull_NameChanged();
            }
        }
        private global::System.String _Full_Name;
        partial void OnFull_NameChanging(global::System.String value);
        partial void OnFull_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date_of_Birth
        {
            get
            {
                return _Date_of_Birth;
            }
            set
            {
                OnDate_of_BirthChanging(value);
                ReportPropertyChanging("Date_of_Birth");
                _Date_of_Birth = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date_of_Birth");
                OnDate_of_BirthChanged();
            }
        }
        private global::System.String _Date_of_Birth;
        partial void OnDate_of_BirthChanging(global::System.String value);
        partial void OnDate_of_BirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.String _Age;
        partial void OnAgeChanging(global::System.String value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone_Number
        {
            get
            {
                return _Phone_Number;
            }
            set
            {
                OnPhone_NumberChanging(value);
                ReportPropertyChanging("Phone_Number");
                _Phone_Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone_Number");
                OnPhone_NumberChanged();
            }
        }
        private global::System.String _Phone_Number;
        partial void OnPhone_NumberChanging(global::System.String value);
        partial void OnPhone_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street_Address
        {
            get
            {
                return _Street_Address;
            }
            set
            {
                OnStreet_AddressChanging(value);
                ReportPropertyChanging("Street_Address");
                _Street_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street_Address");
                OnStreet_AddressChanged();
            }
        }
        private global::System.String _Street_Address;
        partial void OnStreet_AddressChanging(global::System.String value);
        partial void OnStreet_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip_Code
        {
            get
            {
                return _Zip_Code;
            }
            set
            {
                OnZip_CodeChanging(value);
                ReportPropertyChanging("Zip_Code");
                _Zip_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip_Code");
                OnZip_CodeChanged();
            }
        }
        private global::System.String _Zip_Code;
        partial void OnZip_CodeChanging(global::System.String value);
        partial void OnZip_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_Credits_Complete
        {
            get
            {
                return _Total_Credits_Complete;
            }
            set
            {
                OnTotal_Credits_CompleteChanging(value);
                ReportPropertyChanging("Total_Credits_Complete");
                _Total_Credits_Complete = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_Credits_Complete");
                OnTotal_Credits_CompleteChanged();
            }
        }
        private global::System.String _Total_Credits_Complete;
        partial void OnTotal_Credits_CompleteChanging(global::System.String value);
        partial void OnTotal_Credits_CompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prefered_Location
        {
            get
            {
                return _Prefered_Location;
            }
            set
            {
                OnPrefered_LocationChanging(value);
                ReportPropertyChanging("Prefered_Location");
                _Prefered_Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prefered_Location");
                OnPrefered_LocationChanged();
            }
        }
        private global::System.String _Prefered_Location;
        partial void OnPrefered_LocationChanging(global::System.String value);
        partial void OnPrefered_LocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MBA_Speed
        {
            get
            {
                return _MBA_Speed;
            }
            set
            {
                OnMBA_SpeedChanging(value);
                ReportPropertyChanging("MBA_Speed");
                _MBA_Speed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MBA_Speed");
                OnMBA_SpeedChanged();
            }
        }
        private global::System.String _MBA_Speed;
        partial void OnMBA_SpeedChanging(global::System.String value);
        partial void OnMBA_SpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Student_Type
        {
            get
            {
                return _Student_Type;
            }
            set
            {
                OnStudent_TypeChanging(value);
                ReportPropertyChanging("Student_Type");
                _Student_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Student_Type");
                OnStudent_TypeChanged();
            }
        }
        private global::System.String _Student_Type;
        partial void OnStudent_TypeChanging(global::System.String value);
        partial void OnStudent_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Days_Available
        {
            get
            {
                return _Days_Available;
            }
            set
            {
                OnDays_AvailableChanging(value);
                ReportPropertyChanging("Days_Available");
                _Days_Available = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Days_Available");
                OnDays_AvailableChanged();
            }
        }
        private global::System.String _Days_Available;
        partial void OnDays_AvailableChanging(global::System.String value);
        partial void OnDays_AvailableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Athlete
        {
            get
            {
                return _Athlete;
            }
            set
            {
                OnAthleteChanging(value);
                ReportPropertyChanging("Athlete");
                _Athlete = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Athlete");
                OnAthleteChanged();
            }
        }
        private global::System.String _Athlete;
        partial void OnAthleteChanging(global::System.String value);
        partial void OnAthleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Loans
        {
            get
            {
                return _Loans;
            }
            set
            {
                OnLoansChanging(value);
                ReportPropertyChanging("Loans");
                _Loans = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Loans");
                OnLoansChanged();
            }
        }
        private global::System.String _Loans;
        partial void OnLoansChanging(global::System.String value);
        partial void OnLoansChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="software_projModel", Name="taken")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class taken : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new taken object.
        /// </summary>
        /// <param name="iONA_Student_id">Initial value of the IONA_Student_id property.</param>
        /// <param name="course_D_id">Initial value of the Course_D_id property.</param>
        public static taken Createtaken(global::System.String iONA_Student_id, global::System.String course_D_id)
        {
            taken taken = new taken();
            taken.IONA_Student_id = iONA_Student_id;
            taken.Course_D_id = course_D_id;
            return taken;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IONA_Student_id
        {
            get
            {
                return _IONA_Student_id;
            }
            set
            {
                if (_IONA_Student_id != value)
                {
                    OnIONA_Student_idChanging(value);
                    ReportPropertyChanging("IONA_Student_id");
                    _IONA_Student_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IONA_Student_id");
                    OnIONA_Student_idChanged();
                }
            }
        }
        private global::System.String _IONA_Student_id;
        partial void OnIONA_Student_idChanging(global::System.String value);
        partial void OnIONA_Student_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Course_D_id
        {
            get
            {
                return _Course_D_id;
            }
            set
            {
                if (_Course_D_id != value)
                {
                    OnCourse_D_idChanging(value);
                    ReportPropertyChanging("Course_D_id");
                    _Course_D_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Course_D_id");
                    OnCourse_D_idChanged();
                }
            }
        }
        private global::System.String _Course_D_id;
        partial void OnCourse_D_idChanging(global::System.String value);
        partial void OnCourse_D_idChanged();

        #endregion
    
    }

    #endregion
    
}
